# -*- coding: UTF-8 -*-
# Copyright 2014 Luc Saffre
# This file is part of the commondata library.
# The commondata library is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
# The commondata library is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with the commondata library; if not, see
# <http://www.gnu.org/licenses/>.


from __future__ import unicode_literals


def populate(pg):

    pg.city("1000", "Bruxelles", "Brussel", "Brüssel", "Brussels")
    pg.city("1020", "Brussel 2", "", "", "")
    pg.city("1020", "Bruxelles 2", "", "", "")
    pg.city("1020", "Laeken", "", "", "")
    pg.city("1030", "Brussel 3", "", "", "")
    pg.city("1030", "Bruxelles 3", "", "", "")
    pg.city("1030", "Schaarbeek", "", "", "")
    pg.city("1030", "Schaerbeek", "", "", "")
    pg.city("1040", "Brussel 4", "", "", "")
    pg.city("1040", "Bruxelles 4", "", "", "")
    pg.city("1040", "Etterbeek", "", "", "")
    pg.city("1050", "Brussel 5", "", "", "")
    pg.city("1050", "Bruxelles 5", "", "", "")
    pg.city("1050", "Elsene", "", "", "")
    pg.city("1050", "Ixelles", "", "", "")
    pg.city("1060", "Brussel 6", "", "", "")
    pg.city("1060", "Bruxelles 6", "", "", "")
    pg.city("1060", "Saint-Gilles", "", "", "")
    pg.city("1060", "Sint-Gillis", "", "", "")
    pg.city("1070", "Anderlecht", "", "", "")
    pg.city("1070", "Brussel 7", "", "", "")
    pg.city("1070", "Bruxelles 7", "", "", "")
    pg.city("1080", "Brussel 8", "", "", "")
    pg.city("1080", "Bruxelles 8", "", "", "")
    pg.city("1080", "Molenbeek-Saint-Jean", "", "", "")
    pg.city("1080", "Sint-Agatha-Berchem", "", "", "")
    pg.city("1080", "Sint-Jans-Molenbeek", "", "", "")
    pg.city("1081", "Koekelberg", "", "", "")
    pg.city("1082", "Berchem-Sainte-Agathe", "", "", "")
    pg.city("1083", "Ganshoren", "", "", "")
    pg.city("1090", "Brussel 9", "", "", "")
    pg.city("1090", "Bruxelles 9", "", "", "")
    pg.city("1090", "Jette", "", "", "")
    pg.city("1120", "Brussel 12", "", "", "")
    pg.city("1120", "Bruxelles 12", "", "", "")
    pg.city("1120", "Neder-over-Heembeek", "", "", "")
    pg.city("1130", "Brussel 13", "", "", "")
    pg.city("1130", "Bruxelles 13", "", "", "")
    pg.city("1140", "Brussel 14", "", "", "")
    pg.city("1140", "Bruxelles 14", "", "", "")
    pg.city("1140", "Evere", "", "", "")
    pg.city("1150", "Brussel 15", "", "", "")
    pg.city("1150", "Bruxelles 15", "", "", "")
    pg.city("1150", "Sint-Pieters-Woluwe", "", "", "")
    pg.city("1150", "Woluwé-Saint-Pierre", "", "", "")
    pg.city("1160", "Auderghem", "", "", "")
    pg.city("1160", "Brussel 16", "", "", "")
    pg.city("1160", "Bruxelles 16", "", "", "")
    pg.city("1160", "Oudergem", "", "", "")
    pg.city("1170", "Brussel 17", "", "", "")
    pg.city("1170", "Bruxelles 17", "", "", "")
    pg.city("1170", "Watermaal-Bosvoorde", "", "", "")
    pg.city("1170", "Watermael-Boitsfort", "", "", "")
    pg.city("1180", "Brussel 18", "", "", "")
    pg.city("1180", "Bruxelles 18", "", "", "")
    pg.city("1180", "Uccle", "", "", "")
    pg.city("1180", "Ukkel", "", "", "")
    pg.city("1190", "Brussel 19", "", "", "")
    pg.city("1190", "Bruxelles 19", "", "", "")
    pg.city("1190", "Forest", "", "", "")
    pg.city("1190", "Vorst", "", "", "")
    pg.city("1200", "Brussel 20", "", "", "")
    pg.city("1200", "Bruxelles 20", "", "", "")
    pg.city("1200", "Sint-Lambrechts-Woluwe", "", "", "")
    pg.city("1200", "Woluwé-Saint-Lambert", "", "", "")
    pg.city("1210", "Brussel 21", "", "", "")
    pg.city("1210", "Bruxelles 21", "", "", "")
    pg.city("1210", "Saint-Josse-ten-Noode", "", "", "")
    pg.city("1210", "Sint-Joost-ten-Node", "", "", "")
    pg.city("1300", "Limal", "", "", "")
    pg.city("1300", "Wavre", "", "", "")
    pg.city("1301", "Bierges", "", "", "")
    pg.city("1310", "La Hulpe", "Terhulpen", "La Hulpe", "La Hulpe")
    pg.city("1315", "Glimes", "", "", "")
    pg.city("1315", "Incourt", "", "", "")
    pg.city("1315", "Opprebais", "", "", "")
    pg.city("1315", "Piètrebais", "", "", "")
    pg.city("1315", "Roux-Miroir", "", "", "")
    pg.city("1320", "Beauvechain", "", "", "")
    pg.city("1320", "Hamme-Mille", "", "", "")
    pg.city("1320", "L'Ecluse", "", "", "")
    pg.city("1320", "Nodebais", "", "", "")
    pg.city("1320", "Tourinnes-la-Grosse", "", "", "")
    pg.city("1325", "Bonlez", "", "", "")
    pg.city("1325", "Chaumont-Gistoux", "", "", "")
    pg.city("1325", "Corroy-le-Grand", "", "", "")
    pg.city("1325", "Dion-Valmont", "", "", "")
    pg.city("1325", "Longueville", "", "", "")
    pg.city("1330", "Rixensart", "", "", "")
    pg.city("1331", "Rosières", "", "", "")
    pg.city("1332", "Genval", "", "", "")
    pg.city("1340", "Ottignies", "", "", "")
    pg.city("1341", "Céroux-Mousty", "", "", "")
    pg.city("1342", "Limelette", "", "", "")
    pg.city("1348", "Louvain-la-Neuve", "Louvain-la-Neuve", "Neu-Löwen", "Neu-Löwen")
    pg.city("1350", "Enines", "", "", "")
    pg.city("1350", "Folx-les-Caves", "", "", "")
    pg.city("1350", "Jandrain-Jandrenouille", "", "", "")
    pg.city("1350", "Jauche", "", "", "")
    pg.city("1350", "Marilles", "", "", "")
    pg.city("1350", "Noduwez", "", "", "")
    pg.city("1350", "Orp-Jauche", "", "", "")
    pg.city("1350", "Orp-le-Grand", "", "", "")
    pg.city("1357", "Hélécine", "", "", "")
    pg.city("1357", "Linsmeau", "", "", "")
    pg.city("1357", "Neerheylissem", "", "", "")
    pg.city("1357", "Opheylissem", "", "", "")
    pg.city("1360", "Malèves-Ste-Marie-Wastines", "", "", "")
    pg.city("1360", "Orbais", "", "", "")
    pg.city("1360", "Thorembais-les-Béguines", "", "", "")
    pg.city("1360", "Thorembais-Saint-Trond", "", "", "")
    pg.city("1360", "Perwez", "Perwijs", "Perwez", "Perwez")
    pg.city("1367", "Autre-Eglise", "", "", "")
    pg.city("1367", "Bomal (Bt.)", "", "", "")
    pg.city("1367", "Geest-Gérompont-Pt-Rosière", "", "", "")
    pg.city("1367", "Gérompont", "", "", "")
    pg.city("1367", "Grand-Rosière-Hottomont", "", "", "")
    pg.city("1367", "Huppaye", "", "", "")
    pg.city("1367", "Mont-Saint-André", "", "", "")
    pg.city("1367", "Ramillies", "", "", "")
    pg.city("1370", "Dongelberg", "", "", "")
    pg.city("1370", "Jauchelette", "", "", "")
    pg.city("1370", "Jodoigne", "", "", "")
    pg.city("1370", "Jodoigne-Souveraine", "", "", "")
    pg.city("1370", "Lathuy", "", "", "")
    pg.city("1370", "Mélin", "", "", "")
    pg.city("1370", "Piétrain", "", "", "")
    pg.city("1370", "Saint-Jean-Geest", "", "", "")
    pg.city("1370", "Saint-Remy-Geest", "", "", "")
    pg.city("1370", "Zétrud-Lumay", "", "", "")
    pg.city("1380", "Couture-Saint-Germain", "", "", "")
    pg.city("1380", "Lasne", "", "", "")
    pg.city("1380", "Lasne-Chapelle-St-Lambert", "", "", "")
    pg.city("1380", "Maransart", "", "", "")
    pg.city("1380", "Ohain", "", "", "")
    pg.city("1380", "Plancenoit", "", "", "")
    pg.city("1390", "Archennes", "", "", "")
    pg.city("1390", "Biez", "", "", "")
    pg.city("1390", "Bossut-Gottechain", "", "", "")
    pg.city("1390", "Grez-Doiceau", "", "", "")
    pg.city("1390", "Nethen", "", "", "")
    pg.city("1400", "Monstreux", "", "", "")
    pg.city("1400", "Nivelles", "Nijvel", "Nivelles", "Nivelles")
    pg.city("1401", "Baulers", "", "", "")
    pg.city("1402", "Thines", "", "", "")
    pg.city("1404", "Bornival", "", "", "")
    pg.city("1410", "Waterloo", "", "", "")
    pg.city("1420", "Braine-l'Alleud", "", "", "")
    pg.city("1421", "Ophain-Bois-Seigneur-Isaac", "", "", "")
    pg.city("1428", "Lillois-Witterzée", "", "", "")
    pg.city("1430", "Bierghes", "", "", "")
    pg.city("1430", "Quenast", "", "", "")
    pg.city("1430", "Rebecq", "", "", "")
    pg.city("1430", "Rebecq-Rognon", "", "", "")
    pg.city("1435", "Corbais", "", "", "")
    pg.city("1435", "Hévillers", "", "", "")
    pg.city("1435", "Mont-Saint-Guibert", "", "", "")
    pg.city("1440", "Braine-le-Château", "", "", "")
    pg.city("1440", "Wauthier-Braine", "", "", "")
    pg.city("1450", "Chastre", "", "", "")
    pg.city("1450", "Chastre-Villeroux-Blanmont", "", "", "")
    pg.city("1450", "Cortil-Noirmont", "", "", "")
    pg.city("1450", "Gentinnes", "", "", "")
    pg.city("1450", "Saint-Géry", "", "", "")
    pg.city("1457", "Nil-St-Vincent-St-Martin", "", "", "")
    pg.city("1457", "Tourinnes-Saint-Lambert", "", "", "")
    pg.city("1457", "Walhain", "", "", "")
    pg.city("1457", "Walhain-Saint-Paul", "", "", "")
    pg.city("1460", "Ittre", "", "", "")
    pg.city("1460", "Virginal-Samme", "", "", "")
    pg.city("1461", "Haut-Ittre", "", "", "")
    pg.city("1470", "Baisy-thy", "", "", "")
    pg.city("1470", "Bousval", "", "", "")
    pg.city("1470", "Genepiën", "Genappe", "Genappe", "Genappe")
    pg.city("1471", "Loupoigne", "", "", "")
    pg.city("1472", "Vieux-Genappe", "", "", "")
    pg.city("1473", "Glabais", "", "", "")
    pg.city("1474", "Ways", "", "", "")
    pg.city("1476", "Houtain-le-Val", "", "", "")
    pg.city("1480", "Clabecq", "", "", "")
    pg.city("1480", "Oisquercq", "", "", "")
    pg.city("1480", "Saintes", "", "", "")
    pg.city("1480", "Tubize", "", "", "")
    pg.city("1490", "Court-Saint-Etienne", "", "", "")
    pg.city("1495", "Marbais (Bt.)", "", "", "")
    pg.city("1495", "Mellery", "", "", "")
    pg.city("1495", "Sart-Dames-Avelines", "", "", "")
    pg.city("1495", "Tilly", "", "", "")
    pg.city("1495", "Villers-la-Ville", "", "", "")
    pg.city("1500", "Halle", "Hal", "Halle", "Halle")
    pg.city("1501", "Buizingen", "", "", "")
    pg.city("1502", "Lembeek", "", "", "")
    pg.city("1540", "Herfelingen", "", "", "")
    pg.city("1540", "Herne", "", "", "")
    pg.city("1541", "Sint-Pieters-Kapelle (Bt.)", "", "", "")
    pg.city("1547", "Biévène", "", "", "")
    pg.city("1547", "Biévène", "Bever", "Bever", "Bever")
    pg.city("1560", "Hoeilaart", "", "", "")
    pg.city("1570", "Tollembeek", "", "", "")
    pg.city("1570", "Vollezele", "", "", "")
    pg.city("1570", "Gammerages", "Galmaarden", "Galmaarden", "Galmaarden")
    pg.city("1600", "Oudenaken", "", "", "")
    pg.city("1600", "Sint-Laureins-Berchem", "", "", "")
    pg.city("1600", "Sint-Pieters-Leeuw", "", "", "")
    pg.city("1601", "Ruisbroek (Bt.)", "", "", "")
    pg.city("1602", "Vlezenbeek", "", "", "")
    pg.city("1620", "Drogenbos", "", "", "")
    pg.city("1630", "Linkebeek", "", "", "")
    pg.city("1640", "Rhode-Saint-Genèse", "", "", "")
    pg.city("1640", "Sint-Genesius-Rode", "", "", "")
    pg.city("1650", "Beersel", "", "", "")
    pg.city("1651", "Lot", "", "", "")
    pg.city("1652", "Alsemberg", "", "", "")
    pg.city("1653", "Dworp", "", "", "")
    pg.city("1654", "Huizingen", "", "", "")
    pg.city("1670", "Bogaarden", "", "", "")
    pg.city("1670", "Heikruis", "", "", "")
    pg.city("1670", "Pepingen", "", "", "")
    pg.city("1671", "Elingen", "", "", "")
    pg.city("1673", "Beert", "", "", "")
    pg.city("1674", "Bellingen", "", "", "")
    pg.city("1700", "Dilbeek", "", "", "")
    pg.city("1700", "Sint-Martens-Bodegem", "", "", "")
    pg.city("1700", "Sint-Ulriks-Kapelle", "", "", "")
    pg.city("1701", "Itterbeek", "", "", "")
    pg.city("1702", "Groot-Bijgaarden", "", "", "")
    pg.city("1703", "Schepdaal", "", "", "")
    pg.city("1730", "Asse", "", "", "")
    pg.city("1730", "Bekkerzeel", "", "", "")
    pg.city("1730", "Kobbegem", "", "", "")
    pg.city("1730", "Mollem", "", "", "")
    pg.city("1731", "Relegem", "", "", "")
    pg.city("1731", "Zellik", "", "", "")
    pg.city("1740", "Ternat", "", "", "")
    pg.city("1741", "Wambeek", "", "", "")
    pg.city("1742", "Sint-Katherina-lombeek", "", "", "")
    pg.city("1745", "Mazenzele", "", "", "")
    pg.city("1745", "Opwijk", "", "", "")
    pg.city("1750", "Gaasbeek", "", "", "")
    pg.city("1750", "Lennik", "", "", "")
    pg.city("1750", "Sint-Kwintens-Lennik", "", "", "")
    pg.city("1750", "Sint-Martens-Lennik", "", "", "")
    pg.city("1755", "Gooik", "", "", "")
    pg.city("1755", "Kester", "", "", "")
    pg.city("1755", "Leerbeek", "", "", "")
    pg.city("1755", "Oetingen", "", "", "")
    pg.city("1760", "Onze-Lieve-Vrouw-Lombeek", "", "", "")
    pg.city("1760", "Pamel", "", "", "")
    pg.city("1760", "Roosdaal", "", "", "")
    pg.city("1760", "Strijtem", "", "", "")
    pg.city("1761", "Borchtlombeek", "", "", "")
    pg.city("1770", "Liedekerke", "", "", "")
    pg.city("1780", "Wemmel", "", "", "")
    pg.city("1785", "Brussegem", "", "", "")
    pg.city("1785", "Hamme (Bt.)", "", "", "")
    pg.city("1785", "Merchtem", "", "", "")
    pg.city("1790", "Affligem", "", "", "")
    pg.city("1790", "Essene", "", "", "")
    pg.city("1790", "Hekelgem", "", "", "")
    pg.city("1790", "Teralfene", "", "", "")
    pg.city("1800", "Peutie", "", "", "")
    pg.city("1800", "Vilvorde", "Vilvoorde", "Vilvoorde", "Vilvoorde")
    pg.city("1820", "Melsbroek", "", "", "")
    pg.city("1820", "Perk", "", "", "")
    pg.city("1820", "Steenokkerzeel", "", "", "")
    pg.city("1830", "Machelen (Bt)", "", "", "")
    pg.city("1831", "Diegem", "", "", "")
    pg.city("1840", "Londerzeel", "", "", "")
    pg.city("1840", "Malderen", "", "", "")
    pg.city("1840", "Steenhuffel", "", "", "")
    pg.city("1850", "Grimbergen", "", "", "")
    pg.city("1851", "Humbeek", "", "", "")
    pg.city("1852", "Beigem", "", "", "")
    pg.city("1853", "Strombeek-Bever", "", "", "")
    pg.city("1860", "Meise", "", "", "")
    pg.city("1861", "Wolvertem", "", "", "")
    pg.city("1880", "Kapelle-op-den-Bos", "", "", "")
    pg.city("1880", "Nieuwenrode", "", "", "")
    pg.city("1880", "Ramsdonk", "", "", "")
    pg.city("1910", "Berg (Bt.)", "", "", "")
    pg.city("1910", "Buken", "", "", "")
    pg.city("1910", "Kampenhout", "", "", "")
    pg.city("1910", "Nederokkerzeel", "", "", "")
    pg.city("1930", "Nossegem", "", "", "")
    pg.city("1930", "Zaventem", "", "", "")
    pg.city("1931", "Brucargo", "", "", "")
    pg.city("1932", "Sint-Stevens-Woluwe", "", "", "")
    pg.city("1933", "Sterrebeek", "", "", "")
    pg.city("1950", "Kraainem", "", "", "")
    pg.city("1970", "Wezembeek-Oppem", "", "", "")
    pg.city("1980", "Eppegem", "", "", "")
    pg.city("1980", "Zemst", "", "", "")
    pg.city("1981", "Hofstade (Bt.)", "", "", "")
    pg.city("1982", "Elewijt", "", "", "")
    pg.city("1982", "Weerde", "", "", "")

